### ISSUE TITLE
Make Flask-debugtoolbar available

### ISSUE THREAD

**Issue by jace** [hasgeek/baseframe#100]
Moved from hasgeek/coaster#65, originally by @sindhus

It would be handy to have [Flask-debugtoolbar]() available across all our Flask apps. Would be very handy to be able to see [SQL queries being executed with a request](http://flask-debugtoolbar.readthedocs.org/en/latest/panels.html#sqlalchemy), especially in Hasjob.

**Comment by jace** [comment]
To use, add `DEBUG_TB_ENABLED = True` to development.py. We do not set `app.debug = True` in our apps until _after_ this extension is enabled, so it won't pick it up automatically when using `runserver.py`.

**Comment by sindhus** [comment]
In my baseframe repo (which was setup with `python setup.py dev`) I did a `git pull` and got baseframe commit bringing in Flask-debugtoolbar. I then added `DEBUG_TB_ENABLED = True` to `instance/development.py` and restarted hasjob server with an logic error in my index.py code, I only see the Werkzeug debugger but not the toolbar. What am I doing wrong?

**Comment by jace** [comment]
The toolbar appears on regular pages, not debugger pages. The debugger already has all the info you need.
