### ISSUE TITLE
Forms should have a `set_queries` method

### ISSUE THREAD

**Issue by jace** [hasgeek/baseframe#145]
When a form uses `QuerySelectField` or `QuerySelectMultipleField`, it may specify either a `query_factory` in the form class, or a `query` function in the form instance. The latter is used when the query must take context into account.

As a pattern, we prefer query construction in the form itself rather in the view (see #112). We do this by overriding `__init__` and setting `self.field.query` after calling `super`. This is a bit clumsy as it masks the form's calling pattern (as using `*args, **kwargs` hides details from `inspect`). The base class's `__init__` should instead call `self.set_queries()` and provide an empty function, which form classes can override to set queries, without needing to accept arbitrary parameters or call `super`.

**Comment by shreyas-satish** [comment]
Why `set_queries()` and not `set_query`?

**Comment by jace** [comment]
Because there may be more than one query select field.

**Comment by shreyas-satish** [comment]
https://github.com/hasgeek/baseframe/pull/148

**Comment by shreyas-satish** [comment]
https://github.com/hasgeek/baseframe/pull/148 fixes this.
