### ISSUE TITLE
Webmail domains list should be deprecated

### ISSUE THREAD

**Issue by jace** [hasgeek/baseframe#170]
An analysis of Baseframe's `webmail_domains` list using [mxsniff](/jace/mxsniff) today showed that the list was wildly inaccurate, featuring many domains with no MX records at all (meaning they're very likely not email services at all), and some using Google G Suite and other commercial mail hosting services.

Since some webmail services like Mailinator insist on keeping their list of domains secret, there is a low chance the webmail domain list will ever be good enough. However, we can get better accuracy by compiling a list of MX servers for public email services, instead. mxsniff now includes this feature in release 0.3.1 (jace/mxsniff#4), so we should deprecate Baseframe's list, provide a helper function to wrap mxsniff's scanner, and switch over in all apps that use it (notably Hasjob).

**Comment by iambibhas** [comment]
@jace you mean instead of maintaining a list of webmail services, let's maintain a list of mx servers, and then in the apps, look up mx servers for the given email address and see if they are in our maintained list?

**Comment by jace** [comment]
The mxsniff project already exists. Just call it and see if the webmail flag is set in the result.

**Comment by jace** [comment]
@iambibhas Please remove the webmail list from staticdata before closing this ticket.

**Comment by jace** [comment]
References to be removed: https://github.com/search?q=org%3Ahasgeek+webmail_domains&type=Code
