### ISSUE TITLE
Switch from Flask-BabelEx to Flask-Babel

### ISSUE THREAD

**Issue by jace** [hasgeek/baseframe#181]
[Flask-BabelEx](https://github.com/mrjoes/flask-babelex) is not regularly maintained anymore, while [Flask-Babel](https://github.com/python-babel/flask-babel) is up to date. We should switch after confirming feature compatibility, since the reasons for using BabelEx over Babel are no longer clear (introduced in commit 13e8be47f1a6aa28a9266b140464ee3ff832a2a1).

**Comment by jace** [comment]
The switch must be coordinated with Flask-Lastuser and Hasjob, both of which have a dependency on Flask-BabelEx.

**Comment by jace** [comment]
The primary advantage of Flask-BabelEx has still not been solved in Flask-Babel: translations being loaded on every request. https://github.com/python-babel/flask-babel/issues/154

**Comment by iambibhas** [comment]
Another thing missing in Flask-Babel, is lack of domain support https://github.com/python-babel/flask-babel/pull/148

**Comment by jace** [comment]
We have created our own fork [combining Flask-Babel and Flask-BabelEx](/hasgeek/flask-babelhg).
