### ISSUE TITLE
Replace the country list in staticdata with an external library

### ISSUE THREAD

**Issue by jace** [hasgeek/baseframe#203]
The `pycountry` library contains all the static data we want in Baseframe and apps: countries, languages and currencies. All uses of Baseframe's static list in apps should be replaced with `pycountry` (or a similar library) and the list should be removed here.

**Comment by jace** [comment]
@iambibhas wasn't this resolved?

**Comment by iambibhas** [comment]
Don't think so. We removed the webmail domains, but this remains.
