### ISSUE TITLE
Enterprise emails as protonmail are getting marked as public emails

### ISSUE THREAD

**Issue by harishvishwakarma** [hasgeek/baseframe#232]
While posting a job, if I use any enterprise email domains provided by protonmail, its getting marked as public email and getting the message ```Public webmail accounts like Gmail are not accepted. Please use your corporate email address```

**Comment by jace** [comment]
Apologies for missing this. Can you give me a domain to test with?

**Comment by jace** [comment]
@harishvishwakarma I'll need a Protonmail-hosted domain to test this with.

**Comment by harishvishwakarma** [comment]
harish@borndigital.ltd Lets test with this @jace
