### ISSUE TITLE
Update to Bootstrap 3.1

### ISSUE THREAD

**Issue by jace** [hasgeek/baseframe#58]
Bootstrap 3.1 has been out for a while. We are on 3.0. We should upgrade. Bootstrap 3.1 also includes Sass support, so we no longer need to work with static files, but that is a later update.

**Comment by shreyas-satish** [comment]
Upgrading to Bootstrap 3.3.1:
https://github.com/hasgeek/baseframe/issues/70
https://github.com/hasgeek/baseframe/pull/76
