### ISSUE TITLE
Revised networkbar

### ISSUE THREAD

**Issue by shreyas-satish** [hasgeek/baseframe#64]
The new version of the networkbar will probably look like this:

![hg_new_networkbar](https://cloud.githubusercontent.com/assets/380688/5228284/ff30a1b2-772d-11e4-9dbf-43d17fc92b69.png)
1. One navigation menu on a HasGeek site. The site's icon is going to be on the left, followed by the site's navigation items, the HasGeek app drop-down and then the user login.
2. The HasGeek app drop-down (data sourced from hascore) is going to be standard across all HasGeek applications.

**Comment by jace** [comment]
This ticket is obsolete since the networkbar is now gone. We're consolidating down to just two websites: HasGeek and Hasjob.
