### ISSUE TITLE
Inaccessible URL

### ISSUE THREAD

**Issue by shreyas-satish** [hasgeek/baseframe#77]
This issue concerns the ValidUrl class in the validators module. 

http://www.bitcot.com/ is an example URL that is currently accessible, but for which Hasjob reports as inaccessible. The error is reproducible on development, and the request call (when run in the console) returns 200.

    requests.get('http://www.bitcot.com/', timeout=30, allow_redirects=True, verify=False, headers={'User-Agent': 'HasGeek/linkchecker'})

**Comment by jace** [comment]
The requests call is HEAD, not GET. What is the error you get then?

Programmers mis-implementing HEAD is far too common.

**Comment by shreyas-satish** [comment]
Right, so head returns 404. https://github.com/hasgeek/baseframe/pull/78 fixes this particular problem.

**Comment by shreyas-satish** [comment]
Fixed in https://github.com/hasgeek/baseframe/commit/b4eec6ac9dde5cb713bf7e0b5ed7d8b76a28a894
